server:
  port: #TODO:端口号
spring:
  application:
    name: czystudy
  datasource:
    url: jdbc:mysql://mysql:3306/czy-blog-system?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: #TODO:你的数据库密码
  redis:
    host:  redis # Redis服务器地址
    port:  6379 # Redis服务器连接端口
    password:  # TODO:你的Redis服务器连接密码
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    root: warn

mybatis-plus:
  mapper-locations: classpath:net/sjw/blog/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

czy.blog.images.save-path: /usr/app/upload
czy:
  blog:
    domain-cookie: # TODO:最好不要设置
elasticsearch: # TODO:你的搜索引擎的ip地址和端口号